### ISSUE TITLE
Symbol's function definition is void: org2jekyll-input-directory

### ISSUE THREAD

**Issue by ryukinix** [ardumont/org2jekyll#48]
On emacs startup, during loading my emacs script for config this package, I receive this warning. Seems weird for me, because I did read the source and just found this function, but something strange is happened. 

My setup is:
```elisp
(require 'org)
(require 'org2jekyll)

(custom-set-variables '(org2jekyll-blog-author "Manoel Vilela")
                      '(org2jekyll-source-directory "D:/Users/Manoel/Dropbox/Programming/Projects/Websiste/Org")
                      '(org2jekyll-jekyll-directory "d:/Users/Manoel/Dropbox/Programming/Projects/Website/ryukinix.github.io")
                      '(org2jekyll-jekyll-drafts-dir "")
                      '(org2jekyll-jekyll-posts-dir "_posts/")
                      '(org-publish-project-alist
                        `(("default"
                           :base-directory ,(org2jekyll-input-directory)
                           :base-extension "org"
                           :publishing-directory ,(org2jekyll-output-directory)
                           :publishing-function org-html-publish-to-html
                           :headline-levels 4
                           :section-numbers nil
                           :with-toc nil
                           :html-head "<link rel=\"stylesheet\" href=\"./css/style.css\" type=\"text/css\"/>"
                           :html-preamble t
                           :recursive t
                           :make-index t
                           :html-extension "html"
                           :body-only t)
                          ("post"
                           :base-directory ,(org2jekyll-input-directory)
                           :base-extension "org"
                           :publishing-directory ,(org2jekyll-output-directory org2jekyll-jekyll-posts-dir)
                           :publishing-function org-html-publish-to-html
                           :headline-levels 4
                           :section-numbers nil
                           :with-toc nil
                           :html-head "<link rel=\"stylesheet\" href=\"./css/style.css\" type=\"text/css\"/>"
                           :html-preamble t
                           :recursive t
                           :make-index t
                           :html-extension "html"
                           :body-only t)
                          ("images"
                           :base-directory ,(org2jekyll-input-directory "img")
                           :base-extension "jpg\\|gif\\|png"
                           :publishing-directory ,(org2jekyll-output-directory "img")
                           :publishing-function org-publish-attachment
                           :recursive t)
                          ("js"
                           :base-directory ,(org2jekyll-input-directory "js")
                           :base-extension "js"
                           :publishing-directory ,(org2jekyll-output-directory "js")
                           :publishing-function org-publish-attachment
                           :recursive t)
                          ("css"
                           :base-directory ,(org2jekyll-input-directory "css")
                           :base-extension "css\\|el"
                           :publishing-directory ,(org2jekyll-output-directory "css")
                           :publishing-function org-publish-attachment
                           :recursive t)
                          ("web" :components ("images" "js" "css")))))
```

BTW, great tool. 

System info:
* OS: Windows 10 x86_64
* Emacs: Emacs 25.2.1
* Package: org2jekyll 20170225.115

**Comment by ardumont** [comment]
Hello,

> On emacs startup,...

After cleaning up my .emacs.d config's dependencies (following your issue :), i do happen to reproduce this.
I might have misunderstood something about the custom loading and the function definition order.

For example, if the function definition loading would happen after setting the customs (or something similar), this message would make sense.

I need to check this.

Thanks for raising concern.

> BTW, great tool.

Thanks!

Cheers,

**Comment by ryukinix** [comment]
Great! I loved the this way to blog with Jekkyl. Org is just too great to only use for organization, blogging with it would be awesome. Update this issue, please, when you has time to fix that. 

Cheers for you too.

**Comment by ardumont** [comment]
> Great! I loved the this way to blog with Jekkyl. Org is just too great to only use for organization, blogging with it would be awesome. 

Yes, it's nice :)

> Update this issue, please, when you has time to fix that.

It's possibly more an emacs user setup issue (which i bite as well :) than an org2jekyll one.
Probably, my error here is the way i provide ways for the user to setup its customs...

Anyway, here is my insight for the moment of what happens on my side.
There exists an emacs variable named  `custom-file`.
On my setup (some form or prelude), that value is `custom.el`.
The thing is that the customization system (from emacs) dumps that file custom.el (for example after a package installation) with all the customs defined in memory at the time (including my org2jekyll's customs)
And, still in my setup, at startup time, this loads first prelude, then the custom.el file, then the remaining modes i want. Thus the failure. org2jekyll is not yet required at that time...

You could check that you have a similar behavior in your ~/.emacs.d/init.el** or ~/.emacs routines.

I did not find a proper way to override this behavior for now (well, except for changing the load order).
But of course, this solution is dependent on my setup.

Maybe we could override this using `setq` instead of `custom-set-variables` form.
Something like:

```
(setq org2jekyll-blog-author "Manoel Vilela"
      org2jekyll-source-directory "D:/Users/Manoel/Dropbox/Programming/Projects/Websiste/Org"
      org2jekyll-jekyll-directory "d:/Users/Manoel/Dropbox/Programming/Projects/Website/ryukinix.github.io"
      org2jekyll-jekyll-drafts-dir ""
      org2jekyll-jekyll-posts-dir "_posts/"
      org-publish-project-alist
      `(("default"
         :base-directory ,(org2jekyll-input-directory)
         :base-extension "org"
         :publishing-directory ,(org2jekyll-output-directory)
         :publishing-function org-html-publish-to-html
         :headline-levels 4
         :section-numbers nil
         :with-toc nil
         :html-head "<link rel=\"stylesheet\" href=\"./css/style.css\" type=\"text/css\"/>"
         :html-preamble t
         :recursive t
         :make-index t
         :html-extension "html"
         :body-only t)
        ("post"
         :base-directory ,(org2jekyll-input-directory)
         :base-extension "org"
         :publishing-directory ,(org2jekyll-output-directory org2jekyll-jekyll-posts-dir)
         :publishing-function org-html-publish-to-html
         :headline-levels 4
         :section-numbers nil
         :with-toc nil
         :html-head "<link rel=\"stylesheet\" href=\"./css/style.css\" type=\"text/css\"/>"
         :html-preamble t
         :recursive t
         :make-index t
         :html-extension "html"
         :body-only t)
        ("images"
         :base-directory ,(org2jekyll-input-directory "img")
         :base-extension "jpg\\|gif\\|png"
         :publishing-directory ,(org2jekyll-output-directory "img")
         :publishing-function org-publish-attachment
         :recursive t)
        ("js"
         :base-directory ,(org2jekyll-input-directory "js")
         :base-extension "js"
         :publishing-directory ,(org2jekyll-output-directory "js")
         :publishing-function org-publish-attachment
         :recursive t)
        ("css"
         :base-directory ,(org2jekyll-input-directory "css")
         :base-extension "css\\|el"
         :publishing-directory ,(org2jekyll-output-directory "css")
         :publishing-function org-publish-attachment
         :recursive t)
        ("web" :components ("images" "js" "css"))))
```

This works on my part.
I read somewhere (maybe gnu emacs' doc) that that was not ideal though. 
At least, it gets the job done.

--

I guess another simpler possibility would be to avoid using the org2jekyll functions and repeat the wanted path in the different entry mentioning a directory.

Does any of those help you?

--

As another note, attacking the problem from an org2jekyll issue point of view, i tried to define those functions as `autoload`. That means that if you use those, automatically, emacs will require the mode what's needed (which should not be necessary since the customs already define this...)
Anyway, here i open another can of worms, i have a cyclic dependency with org or some form of it.
So i'd rather not go that way :)

Cheers,

**Comment by ryukinix** [comment]
Yes, this really helped me. Your setup worked very well. You could close that issue.

Thanks a lot for the help.
