### ISSUE TITLE
Dummy tags persisting even with tags:nil

### ISSUE THREAD

**Issue by ibynx** [ardumont/org2jekyll#58]
Hi,
The HTML file that org2jekyll outputs contains the "dummy-tags-should-be-removed" thing, even though I have set `tags:nil`.
My full options line is `#+OPTIONS: tags:nil toc:nil timestamps:t`. I'm probably just not doing something right. The relevant HTML section:
```
---
tags: 
- 
- 
- 
- 
- 
- 
- dummy-tags-should-be-replaced
---
```

Thanks!

**Comment by ardumont** [comment]
Hello, looks like a bug alright. 
Thanks for the report.

I'll have a look to see if I see anything strikingly wrong on org2jekyll's side ;)

In the mean time, if you have the latest version, could you please report the
output of `M-x org2jekyll-bug-report`?

Thanks

**Comment by ardumont** [comment]
Without any code reading already, just reflecting.

The first thing that hits me is that I don't recall the meaning of org-mode's
"tags" (in the main header) [1]. So most possibly, it's the root source of the
problem ¯\_(ツ)_/¯.

org2jekyll simply acts on the `#+TAGS` entry whether `tags` is configured to
something or not. So that need enhancement to respect the user's buffer setup.

(added the label enhancement)

Reading again the orgmode page, the `#+TAGS` property should be a list of words
separated by space. In org2jekyll, it's expected to be csv... So another improvment
incoming as well for that part.

[1] https://orgmode.org/manual/Setting-Tags.html
pp

**Comment by ardumont** [comment]
Following analysis from your report, i faced some inconsistencies.

I have fixed those including respecting the user setup.
A new version 0.2.1 got released.

Please, upgrade and check the problem mentioned no longer appears ;)

Cheers,

**Comment by ibynx** [comment]
It's working perfectly now. Je vous remercie beaucoup pour votre réponse super vite!

**Comment by ardumont** [comment]
Awesome, thanks for the heads up.
